In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1=pd.read_csv('customers.csv')
df2=pd.read_csv('finance_transactions.csv')

In [3]:
display(df1.head())

,customer_id,fisrt_name,second_name,gender,date_of_birth,city,state,occupation,customer_segment,annual_income,join_date
0,C00001,Karan,Chopra,Male,09-10-1982,Kolkata,West Bengal,Retired,SME,988416.79,15-04-2021
1,C00002,Ishaan,Patel,Male,07-10-1983,Chandigarh,Chandigarh,Salaried,Premium,457149.28,06-04-2022
2,C00003,Krishna,Patel,Male,27-11-1989,Hyderabad,Telangana,Retired,Retail,378907.24,06-03-2026
3,C00004,Amit,Verma,Male,13-08-1970,Lucknow,Uttar Pradesh,Salaried,Retail,299085.16,16-07-2021
4,C00005,Reyansh,Jain,Female,07-02-1977,Ahmedabad,Gujarat,Freelancer,SME,775436.07,23-02-2023

In [4]:
display(df2.head())

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
0,T00000001,21-02-2025,A001795,C00629,Investment,Mobile App,Food Delivery,24721.24,123.61,22.25,INR,Success,No,63,REF8835851139
1,T00000002,28-01-2023,A004859,C02038,Transfer,UPI,Groceries,18711.77,93.56,16.84,INR,Success,No,21,REF9409811139
2,T00000003,25-06-2024,A003081,C00652,Transfer,Net Banking,Groceries,45865.90,0.00,0.00,INR,Success,No,25,REF1704628312
3,T00000004,20-02-2025,A004122,C01357,Withdrawal,Auto Debit,Salary,4310.91,NaN,0.78,INR,Failed,No,43,REF3937614748
4,T00000005,06-08-2024,A004150,C02547,Deposit,Branch,Shopping,11646.45,0.00,0.00,INR,Success,No,5,REF5855288886

In [5]:
df1.isnull().sum()

customer_id         0
fisrt_name          0
second_name         0
gender              0
date_of_birth       0
city                0
state               0
occupation          0
customer_segment    0
annual_income       0
join_date           0
dtype: int64

In [6]:
df2.isnull().sum()

transaction_id         0
transaction_date       0
account_id             0
customer_id            0
transaction_type       0
channel                0
merchant_category      0
amount                 0
fee_amount            24
tax_amount             0
currency               0
transaction_status     0
is_fraud               0
risk_score             0
reference_no           0
dtype: int64

In [7]:
df1.duplicated().sum()

np.int64(0)

In [8]:
df2.duplicated().sum()

np.int64(68)

In [9]:
df2.duplicated(subset=['transaction_id']).sum()

np.int64(69)

In [10]:
df1.shape

(5000, 11)

In [11]:
df2.shape

(50069, 15)

In [12]:
target=df2['transaction_id']
duplicates=df2[df2.duplicated(subset=['transaction_id'], keep=False)]
print(duplicates)

      transaction_id transaction_date account_id customer_id transaction_type  \
8          T00000009       24-09-2024    A006977      C01463         Transfer
9          T00000009       24-09-2024    A006977      C01463         Transfer
14         T00000014       10-08-2024    A004138      C00960         Loan EMI
15         T00000014       10-08-2024    A004138      C00960         Loan EMI
66         T00000065       26-02-2023    A006060      C00103          Deposit
...              ...              ...        ...         ...              ...
50064      T00049879       01-09-2024    A006793      C02066         Transfer
50065      T00049880       27-06-2025    A003754      C01053         Loan EMI
50066      T00049881       02-08-2024    A003657      C02434         Loan EMI
50067      T00049882       13-11-2023    A003840      C03287         Transfer
50068      T00049883       25-02-2025    A007128      C03308     Bill Payment

           channel merchant_category    amount  fee_amount  tax_amount  \
8              ATM              Rent   4237.33         NaN        3.81
9              ATM              Rent   4237.33       21.19        3.81
14             UPI            Travel   9334.16        9.33        1.68
15             UPI            Travel   9334.16        9.33        1.68
66     Net Banking          Shopping   6526.38        0.00        0.00
...            ...               ...       ...         ...         ...
50064  Net Banking          Shopping  11386.50       22.77        4.10
50065          ATM     Entertainment  40959.94       81.92       14.75
50066          ATM         Education   9873.84        9.87        1.78
50067          UPI            Salary  13980.12        0.00        0.00
50068  Net Banking      Bank Charges   2780.85        2.78        0.50

      currency transaction_status is_fraud  risk_score   reference_no
8          INR            Success       No          17  REF7746654436
9          INR            Success       No          17  REF7746654436
14         INR            Success       No          45  REF9776706632
15         INR            Success       No          45  REF9776706632
66         INR            Success       No           5  REF3244794918
...        ...                ...      ...         ...            ...
50064      INR            Success       No          31  REF6074582257
50065      INR            Success       No          17  REF4636170490
50066      INR            Success       No          56  REF6815460792
50067      INR            Success       No          67  REF4683694384
50068      INR            Success       No          25  REF4914886377

[138 rows x 15 columns]

In [13]:
df2.drop_duplicates(subset=['transaction_id'], keep='first', inplace=True)

In [14]:
df2.duplicated().sum()

np.int64(0)

In [15]:
df2.shape

(50000, 15)

In [16]:
df2.isnull().sum()

transaction_id         0
transaction_date       0
account_id             0
customer_id            0
transaction_type       0
channel                0
merchant_category      0
amount                 0
fee_amount            24
tax_amount             0
currency               0
transaction_status     0
is_fraud               0
risk_score             0
reference_no           0
dtype: int64

In [17]:
mean_value=df2['fee_amount'].mean().round(2)
print(mean_value)

14.52

In [18]:
df2['fee_amount']=df2['fee_amount'].fillna(mean_value)

In [19]:
df2.isnull().sum()

transaction_id        0
transaction_date      0
account_id            0
customer_id           0
transaction_type      0
channel               0
merchant_category     0
amount                0
fee_amount            0
tax_amount            0
currency              0
transaction_status    0
is_fraud              0
risk_score            0
reference_no          0
dtype: int64

In [20]:
print(df2['fee_amount'].isnull().sum())

0

In [21]:
df2['channel']

0            Mobile App
1                   UPI
2           Net Banking
3            Auto Debit
4                Branch
              ...
49999        Auto Debit
50000        Mobile App
50001               UPI
50002        Mobile App
50003            Branch
Name: channel, Length: 50000, dtype: str

In [22]:
df2.dtypes

transaction_id            str
transaction_date          str
account_id                str
customer_id               str
transaction_type          str
channel                   str
merchant_category         str
amount                float64
fee_amount            float64
tax_amount            float64
currency                  str
transaction_status        str
is_fraud                  str
risk_score              int64
reference_no              str
dtype: object

In [23]:
df2['transaction_date']=pd.to_datetime(df2['transaction_date'] )

C:\Users\kk\AppData\Local\Temp\ipykernel_17412\4179813370.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df2['transaction_date']=pd.to_datetime(df2['transaction_date'] )

In [24]:
df1.dtypes

customer_id             str
fisrt_name              str
second_name             str
gender                  str
date_of_birth           str
city                    str
state                   str
occupation              str
customer_segment        str
annual_income       float64
join_date               str
dtype: object

In [25]:
df1['date_of_birth'] = pd.to_datetime(
    df1['date_of_birth'],
    format='%d-%m-%Y'
)

df1['join_date'] = pd.to_datetime(
    df1['join_date'],
    format='%d-%m-%Y'
)

In [26]:
df1.dtypes

customer_id                    str
fisrt_name                     str
second_name                    str
gender                         str
date_of_birth       datetime64[us]
city                           str
state                          str
occupation                     str
customer_segment               str
annual_income              float64
join_date           datetime64[us]
dtype: object

In [27]:
df2.dtypes

transaction_id                   str
transaction_date      datetime64[us]
account_id                       str
customer_id                      str
transaction_type                 str
channel                          str
merchant_category                str
amount                       float64
fee_amount                   float64
tax_amount                   float64
currency                         str
transaction_status               str
is_fraud                         str
risk_score                     int64
reference_no                     str
dtype: object

In [28]:
df2.head()

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
0,T00000001,2025-02-21,A001795,C00629,Investment,Mobile App,Food Delivery,24721.24,123.61,22.25,INR,Success,No,63,REF8835851139
1,T00000002,2023-01-28,A004859,C02038,Transfer,UPI,Groceries,18711.77,93.56,16.84,INR,Success,No,21,REF9409811139
2,T00000003,2024-06-25,A003081,C00652,Transfer,Net Banking,Groceries,45865.90,0.00,0.00,INR,Success,No,25,REF1704628312
3,T00000004,2025-02-20,A004122,C01357,Withdrawal,Auto Debit,Salary,4310.91,14.52,0.78,INR,Failed,No,43,REF3937614748
4,T00000005,2024-08-06,A004150,C02547,Deposit,Branch,Shopping,11646.45,0.00,0.00,INR,Success,No,5,REF5855288886

In [29]:
df2['currency'].unique()

<ArrowStringArray>
['INR', 'inr', 'inR']
Length: 3, dtype: str

In [30]:
df2['currency']=df2['currency'].str.upper()

In [31]:
df2['transaction_type'].unique()

<ArrowStringArray>
[     'Investment',        'Transfer',      'Withdrawal',         'Deposit',
        'Loan EMI', 'Interest Credit',    'Card Payment',    'Bill Payment',
      'Fee Charge',          'Refund']
Length: 10, dtype: str

In [32]:
df2['merchant_category'].unique()

<ArrowStringArray>
['Food Delivery',     'Groceries',        'Salary',      'Shopping',
     'Insurance',     'Education',          'Rent',    'Healthcare',
  'Bank Charges',          'Fuel',        'Travel',     'Utilities',
 'Entertainment',   'Mutual Fund']
Length: 14, dtype: str

In [33]:
df2['is_fraud'].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str